package views;

import storage.DatabaseInterface;
import storage.FileStoreInterface;
import web.WebRequest;
import web.WebResponse;

public class Login extends DynamicWebPage
{

	public Login(DatabaseInterface db,FileStoreInterface fs)
	{
		super(db,fs);
	}

	public boolean process(WebRequest toProcess)
	{
		if(toProcess.path.equalsIgnoreCase("Login.html"))
		{
			String stringToSendToWebBrowser = "";
			stringToSendToWebBrowser += "<html>\n";
			stringToSendToWebBrowser += "  \n";
			stringToSendToWebBrowser += "  <head>\n";
			stringToSendToWebBrowser += "    <meta charset=\"utf-8\">\n";
			stringToSendToWebBrowser += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
			stringToSendToWebBrowser += "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n";
			stringToSendToWebBrowser += "    type=\"text/css\">\n";
			stringToSendToWebBrowser += "    <link rel=\"stylesheet\" href=\"https://v40.pingendo.com/assets/4.0.0/default/theme.css\"\n";
			stringToSendToWebBrowser += "    type=\"text/css\">\n";
			stringToSendToWebBrowser += "  </head>\n";
			stringToSendToWebBrowser += "  \n";
			stringToSendToWebBrowser += "  <body>\n";
			stringToSendToWebBrowser += "    <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n";
			stringToSendToWebBrowser += "      <a class=\"navbar-brand\" href=\"#\">Rondot Stories</a>\n";
			stringToSendToWebBrowser += "      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n";
			stringToSendToWebBrowser += "      aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
			stringToSendToWebBrowser += "        <span class=\"navbar-toggler-icon\"></span>\n";
			stringToSendToWebBrowser += "      </button>\n";
			stringToSendToWebBrowser += "      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n";
			stringToSendToWebBrowser += "        <ul class=\"navbar-nav mr-auto\">\n";
			stringToSendToWebBrowser += "          <li class=\"nav-item active\">\n";
			stringToSendToWebBrowser += "            <a class=\"nav-link\" href=\"/Index_Page.html\">Home <span class=\"sr-only\">(current)</span></a>\n";
			stringToSendToWebBrowser += "          </li>\n";
			stringToSendToWebBrowser += "          <li class=\"nav-item\">\n";
			stringToSendToWebBrowser += "            <a class=\"nav-link\" href=\"#\">Account</a>\n";
			stringToSendToWebBrowser += "          </li>\n";
			stringToSendToWebBrowser += "          <li class=\"nav-item\">\n";
			stringToSendToWebBrowser += "            <a class=\"nav-link\" href=\"/UserMessagesPage.html\">Messages</a>\n";
			stringToSendToWebBrowser += "          </li>\n";
			stringToSendToWebBrowser += "        </ul>\n";
			stringToSendToWebBrowser += "        <form class=\"form-inline my-2 my-lg-0\">\n";
			stringToSendToWebBrowser += "          <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\"\n";
			stringToSendToWebBrowser += "          aria-label=\"Search\">\n";
			stringToSendToWebBrowser += "          <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n";
			stringToSendToWebBrowser += "        </form>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </nav>\n";
			stringToSendToWebBrowser += "    <div class=\"py-5 bg-primary\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "            <div class=\"page-header\">\n";
			stringToSendToWebBrowser += "              <h1>\n";
			stringToSendToWebBrowser += "                <b>LOGIN</b>\n";
			stringToSendToWebBrowser += "              </h1>\n";
			stringToSendToWebBrowser += "            </div>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"py-5 bg-primary\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "            <form class=\"form-horizontal\" role=\"form\">\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                  <label for=\"inputEmail3\" class=\"control-label\">Username</label>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <input type=\"text\" class=\"form-control\" id=\"inputUsername\" placeholder=\"Username\">\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                  <label for=\"inputPassword3\" class=\"control-label\">Password</label>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <input type=\"password\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"Password\">\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-offset-2 col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <div class=\"checkbox\">\n";
			stringToSendToWebBrowser += "                    <label>\n";
			stringToSendToWebBrowser += "                      <input type=\"checkbox\">Remember me</label>\n";
			stringToSendToWebBrowser += "                  </div>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-offset-2 col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <button type=\"submit\" class=\"btn btn-default\">Sign in</button>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "            </form>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"py-5 bg-primary\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-3\">\n";
			stringToSendToWebBrowser += "            <a href=\"/Registration_Page.html\" class=\"btn text-center align-items-center align-self-center btn-outline-light\">Dont have an account? Register now\n";
			stringToSendToWebBrowser += "            <br>\n";
			stringToSendToWebBrowser += "          </a>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"bg-primary p-0\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\"></div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"bg-dark text-white\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"p-4 col-md-3\">\n";
			stringToSendToWebBrowser += "            <h2 class=\"mb-4 text-secondary\">Rondot Stories</h2>\n";
			stringToSendToWebBrowser += "            <p class=\"text-white\">A company based on people's stories, adventures and life.</p>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "          <div class=\"p-4 col-md-3\">\n";
			stringToSendToWebBrowser += "            <h2 class=\"mb-4 text-secondary\">Mapsite</h2>\n";
			stringToSendToWebBrowser += "            <ul class=\"list-unstyled\">\n";
			stringToSendToWebBrowser += "              <a href=\"#\" class=\"text-white\">Home</a>\n";
			stringToSendToWebBrowser += "              <br>\n";
			stringToSendToWebBrowser += "              <a href=\"#\" class=\"text-white\">About us</a>\n";
			stringToSendToWebBrowser += "              <br>\n";
			stringToSendToWebBrowser += "              <a href=\"#\" class=\"text-white\">Our services</a>\n";
			stringToSendToWebBrowser += "              <br>\n";
			stringToSendToWebBrowser += "              <a href=\"#\" class=\"text-white\">Stories</a>\n";
			stringToSendToWebBrowser += "            </ul>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "          <div class=\"p-4 col-md-3\">\n";
			stringToSendToWebBrowser += "            <h2 class=\"mb-4\">Contact</h2>\n";
			stringToSendToWebBrowser += "            <p>\n";
			stringToSendToWebBrowser += "              <a href=\"tel:+246 - 542 550 5462\" class=\"text-white\"><i class=\"fa d-inline mr-3 text-secondary fa-phone\"></i>+246 - 542 550 5462</a>\n";
			stringToSendToWebBrowser += "            </p>\n";
			stringToSendToWebBrowser += "            <p>contact@rondotstories.co.uk</p>\n";
			stringToSendToWebBrowser += "            <p>\n";
			stringToSendToWebBrowser += "              <a href=\"https://goo.gl/maps/AUq7b9W7yYJ2\" class=\"text-white\" target=\"_blank\"><i class=\"fa d-inline mr-3 fa-map-marker text-secondary\"></i>18 Malone Rd, Belfast&nbsp;</a>\n";
			stringToSendToWebBrowser += "            </p>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "          <div class=\"p-4 col-md-3\">\n";
			stringToSendToWebBrowser += "            <h2 class=\"mb-4 text-light\">Subscribe</h2>\n";
			stringToSendToWebBrowser += "            <form>\n";
			stringToSendToWebBrowser += "              <fieldset class=\"form-group text-white\">\n";
			stringToSendToWebBrowser += "                <label for=\"exampleInputEmail1\">Get our newsletter</label>\n";
			stringToSendToWebBrowser += "                <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\"\n";
			stringToSendToWebBrowser += "                placeholder=\"Enter email\">\n";
			stringToSendToWebBrowser += "              </fieldset>\n";
			stringToSendToWebBrowser += "              <button type=\"submit\" class=\"btn btn-outline-secondary\">Submit</button>\n";
			stringToSendToWebBrowser += "            </form>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12 mt-3\">\n";
			stringToSendToWebBrowser += "            <p class=\"text-center text-white\">\u00C3\u0082\u00C2\u00A9 Copyright 2018 Rondot - All rights reserved.</p>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"section\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row text-center\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-xs-3 text-center\">\n";
			stringToSendToWebBrowser += "            <a><i class=\"fa fa-5x fa-fw fa-instagram\"></i></a>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "          <div class=\"col-xs-3\">\n";
			stringToSendToWebBrowser += "            <a><i class=\"fa fa-5x fa-fw fa-twitter\"></i></a>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "          <div class=\"col-xs-3\">\n";
			stringToSendToWebBrowser += "            <a><i class=\"fa fa-5x fa-fw fa-facebook\"></i></a>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "          <div class=\"col-xs-3 text-center\">\n";
			stringToSendToWebBrowser += "            <a><i class=\"fa fa-5x fa-fw fa-github\"></i></a>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\n";
			stringToSendToWebBrowser += "    crossorigin=\"anonymous\"></script>\n";
			stringToSendToWebBrowser += "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\n";
			stringToSendToWebBrowser += "    integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\n";
			stringToSendToWebBrowser += "    crossorigin=\"anonymous\"></script>\n";
			stringToSendToWebBrowser += "    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\n";
			stringToSendToWebBrowser += "    integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\n";
			stringToSendToWebBrowser += "    crossorigin=\"anonymous\"></script>\n";
			stringToSendToWebBrowser += "    <pingendo onclick=\"window.open('https://pingendo.com/', '_blank')\"\n";
			stringToSendToWebBrowser += "    style=\"cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:180px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white\">Made with Pingendo&nbsp;&nbsp;\n";
			stringToSendToWebBrowser += "      <img src=\"https://pingendo.com/site-assets/Pingendo_logo_big.png\"\n";
			stringToSendToWebBrowser += "      class=\"d-block\" alt=\"Pingendo logo\" height=\"16\">\n";
			stringToSendToWebBrowser += "    </pingendo>\n";
			stringToSendToWebBrowser += "  </body>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "</html>\n";
			toProcess.r = new WebResponse( WebResponse.HTTP_OK, WebResponse.MIME_HTML, stringToSendToWebBrowser );
			return true;
		}
		return false;
	}

}
